title: ChemHack - Chemnitz Hackathon
email: info@chemhack.de
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codeforchemnitz
github_username:  codeforchemnitz

# Build settings
markdown: kramdown
#theme: default
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
